**Write a NumPy program to create an array of all even integers from 30 to 70**

In [1]:
# Importing the NumPy library with 'np'
import numpy as np

# Creating an array of even integers from 30 to 70 (inclusive) with a step size of 2 using np.arange()
array = np.arange(30, 71, 2)

# Printing a message indicating an array of all the even integers from 30 to 70
print("Array of all the even integers from 30 to 70")

# Printing the array of all the even integers from 30 to 70
print(array)

Array of all the even integers from 30 to 70
[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


**Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution.**

In [2]:
# Importing the NumPy library with an'np'
import numpy as np

# Generating an array of 15 random numbers from a standard normal distribution using np.random.normal()
rand_num = np.random.normal(0, 1, 15)

# Printing a message indicating 15 random numbers from a standard normal distribution
print("15 random numbers from a standard normal distribution:")

# Printing the array of 15 random numbers
print(rand_num)

15 random numbers from a standard normal distribution:
[ 1.03569214  0.30315663 -1.27421569 -1.37541344  1.43960076 -0.51922584
  0.87998741  0.0988791  -0.44583461  0.18992937 -0.79697768 -0.52414543
  0.38219705 -0.29445532 -0.56205986]


**How to compute the cross-product of two matrices in NumPy?**

In [3]:
#For finding the cross product of two given vectors we are using numpy.cross() function of NumPy library.
# import library
import numpy as np

# declare vectors
x = [1, 2]
y = [3, 4]

# find cross product of
# two given vectors
result = np.cross(x, y)

# show the result
print(result)

-2


**How to compute the determinant of an array using NumPy?**

In [5]:
# Import the NumPy library and alias it as 'np'
import numpy as np

# Create a 2x2 NumPy array 'a' containing specific values
a = np.array([[1,2],[3,4]])

# Display the original array 'a'
print("Original array:")
print(a)

# Calculate the determinant of the array 'a' using np.linalg.det() function
result =  np.linalg.det(a)

# Display the determinant of the array 'a'
print("Determinant of the said array:")
print(result)

Original array:
[[1 2]
 [3 4]]
Determinant of the said array:
-2.0000000000000004


**How to create a 3x3x3 array with random values using NumPy?**

In [4]:
# Importing the NumPy library as np

import numpy as np

# Generating a 3x3x3 NumPy array 'x' filled with random floats between 0 and 1 using np.random.random()

x = np.random.random((3, 3, 3))

# Printing the array 'x'
print(x)

[[[0.93312487 0.35130654 0.85115986]
  [0.62449251 0.8239271  0.53369081]
  [0.35519893 0.12754957 0.92093724]]

 [[0.37393492 0.89869905 0.24478536]
  [0.18895331 0.55021379 0.31907802]
  [0.67248222 0.86990724 0.92263597]]

 [[0.41732362 0.62123219 0.86661827]
  [0.62525391 0.27641374 0.7699392 ]
  [0.36094567 0.7965225  0.2631533 ]]]


**How to create a 5x5 array with random values and find the minimum and maximum values using NumPy?**

In [6]:
# Importing the NumPy library as np

import numpy as np

# Generating a 5x5 NumPy array 'x' filled with random floats between 0 and 1 using np.random.random()

x = np.random.random((5, 5))

# Printing the original array 'x'
print("Original Array:")
print(x)

# Calculating the minimum and maximum values in array 'x' using x.min() and x.max() functions
xmin, xmax = x.min(), x.max()

# Printing the minimum and maximum values of the array 'x'
print("Minimum and Maximum Values:")
print(xmin, xmax)

Original Array:
[[0.69809815 0.30918438 0.61073611 0.02551501 0.89779581]
 [0.33133233 0.56527695 0.70362411 0.84010739 0.32221677]
 [0.07137599 0.58611445 0.54809569 0.17966083 0.92388315]
 [0.92515711 0.54830524 0.11671481 0.95577158 0.61859725]
 [0.54617039 0.67924264 0.24500007 0.12665195 0.17041188]]
Minimum and Maximum Values:
0.02551500985600752 0.9557715777164139


**How to compute the mean, standard deviation, and variance of a given array along the second axis in
NumPy?**

In [7]:
# Importing the NumPy library
import numpy as np

# Creating an array 'x' using arange with 6 elements
x = np.arange(6)

# Displaying the original array 'x'
print("\nOriginal array:")
print(x)

# Calculating the mean of the array 'x' using np.mean()
r1 = np.mean(x)

# Calculating the average of the array 'x' using np.average()
r2 = np.average(x)

# Asserting if the results from np.mean() and np.average() are close
assert np.allclose(r1, r2)

# Displaying the calculated mean of the array 'x'
print("\nMean: ", r1)

# Calculating the standard deviation of the array 'x' using np.std()
r1 = np.std(x)

# Calculating the standard deviation manually
r2 = np.sqrt(np.mean((x - np.mean(x)) ** 2))

# Asserting if the results from np.std() and manual calculation are close
assert np.allclose(r1, r2)

# Displaying the calculated standard deviation of the array 'x'
print("\nstd: ", r1)

# Calculating the variance of the array 'x' using np.var()
r1 = np.var(x)

# Calculating the variance manually
r2 = np.mean((x - np.mean(x)) ** 2)

# Asserting if the results from np.var() and manual calculation are close
assert np.allclose(r1, r2)

# Displaying the calculated variance of the array 'x'
print("\nvariance: ", r1)



Original array:
[0 1 2 3 4 5]

Mean:  2.5

std:  1.707825127659933

variance:  2.9166666666666665
